"""update geo models

Revision ID: 3df2f4dfd04a
Revises: 8f8d3fd6442a
Create Date: 2026-08-21 05:58:56.151012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df2f4dfd04a'
down_revision: Union[str, Sequence[str], None] = '8f8d3fd6442a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_districts_division_id'), 'districts', ['division_id'], unique=False)
    op.create_index(op.f('ix_districts_name_en'), 'districts', ['name_en'], unique=False)
    op.create_unique_constraint('uq_district_division_name_en', 'districts', ['division_id', 'name_en'])
    op.drop_constraint('districts_ibfk_1', 'districts', type_='foreignkey')
    op.create_foreign_key(None, 'districts', 'divisions', ['division_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_divisions_name_en'), 'divisions', ['name_en'], unique=True)
    op.create_unique_constraint(None, 'divisions', ['name_bn'])
    op.add_column('unions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_unions_upazila_id'), 'unions', ['upazila_id'], unique=False)
    op.create_unique_constraint('uq_union_upazila_name_en', 'unions', ['upazila_id', 'name_en'])
    op.drop_constraint('unions_ibfk_1', 'unions', type_='foreignkey')
    op.create_foreign_key(None, 'unions', 'upazilas', ['upazila_id'], ['id'], ondelete='CASCADE')
    op.add_column('upazilas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_upazilas_district_id'), 'upazilas', ['district_id'], unique=False)
    op.create_index(op.f('ix_upazilas_name_en'), 'upazilas', ['name_en'], unique=False)
    op.create_unique_constraint('uq_upazila_district_name_en', 'upazilas', ['district_id', 'name_en'])
    op.drop_constraint('upazilas_ibfk_1', 'upazilas', type_='foreignkey')
    op.create_foreign_key(None, 'upazilas', 'districts', ['district_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upazilas', type_='foreignkey')
    op.create_foreign_key('upazilas_ibfk_1', 'upazilas', 'districts', ['district_id'], ['id'])
    op.drop_constraint('uq_upazila_district_name_en', 'upazilas', type_='unique')
    op.drop_index(op.f('ix_upazilas_name_en'), table_name='upazilas')
    op.drop_index(op.f('ix_upazilas_district_id'), table_name='upazilas')
    op.drop_column('upazilas', 'created_at')
    op.drop_constraint(None, 'unions', type_='foreignkey')
    op.create_foreign_key('unions_ibfk_1', 'unions', 'upazilas', ['upazila_id'], ['id'])
    op.drop_constraint('uq_union_upazila_name_en', 'unions', type_='unique')
    op.drop_index(op.f('ix_unions_upazila_id'), table_name='unions')
    op.drop_column('unions', 'created_at')
    op.drop_constraint(None, 'divisions', type_='unique')
    op.drop_index(op.f('ix_divisions_name_en'), table_name='divisions')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.create_foreign_key('districts_ibfk_1', 'districts', 'divisions', ['division_id'], ['id'])
    op.drop_constraint('uq_district_division_name_en', 'districts', type_='unique')
    op.drop_index(op.f('ix_districts_name_en'), table_name='districts')
    op.drop_index(op.f('ix_districts_division_id'), table_name='districts')
    op.drop_column('districts', 'created_at')
    # ### end Alembic commands ###
