"""add hospitals departments doctors

Revision ID: 6cd95dc684e1
Revises: be0009b9305c
Create Date: 2026-08-01 20:00:47.464998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd95dc684e1'
down_revision: Union[str, Sequence[str], None] = 'be0009b9305c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('govt', 'private', 'ngo', name='hospitaltype'), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_by', sa.Integer(), nullable=True),
    sa.Column('data_accuracy_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('opd_days', sa.String(length=255), nullable=True),
    sa.Column('opd_time_start', sa.String(length=255), nullable=True),
    sa.Column('opd_time_end', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('opd_schedule', sa.JSON(), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    op.drop_table('departments')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
