"""no schema change - file upload

Revision ID: 8ca4c73e4d10
Revises: 3df2f4dfd04a
Create Date: 2026-08-22 19:18:29.015043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca4c73e4d10'
down_revision: Union[str, Sequence[str], None] = '3df2f4dfd04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
