"""add institutions table and FK

Revision ID: 91cbe72c79bc
Revises: 8ca4c73e4d10
Create Date: 2026-08-23 16:26:45.132639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cbe72c79bc'
down_revision: Union[str, Sequence[str], None] = '8ca4c73e4d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('nursing_college', 'medical_college', 'university', 'other', name='institutiontype'), nullable=False),
    sa.Column('accreditation_status', sa.Enum('accredited', 'pending', 'unaccredited', name='accreditationstatus'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'volunteer_profiles', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer_profiles', type_='foreignkey')
    op.drop_table('institutions')
    # ### end Alembic commands ###
