"""add symptom checker and help requests

Revision ID: b63cf4a4597a
Revises: 6cd95dc684e1
Create Date: 2026-08-01 20:19:30.900725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63cf4a4597a'
down_revision: Union[str, Sequence[str], None] = '6cd95dc684e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('common_name_bn', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('info', 'serial', 'accommodation', 'ambulance', 'blood', 'emergency', name='helprequesttype'), nullable=False),
    sa.Column('urgency', sa.Enum('normal', 'urgent', 'emergency', name='helprequesturgency'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'inprogress', 'resolved', 'closed', name='helprequeststatus'), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('patient_feedback', sa.Integer(), nullable=True),
    sa.Column('patient_feedback_text', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistance_logs_volunteer_id'), 'assistance_logs', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistance_logs_volunteer_id'), table_name='assistance_logs')
    op.drop_table('assistance_logs')
    op.drop_table('help_requests')
    op.drop_table('symptom_specialties')
    op.drop_table('symptoms')
    op.drop_table('specialties')
    # ### end Alembic commands ###
