"""remove article type, use category only

Revision ID: bc589adf566c
Revises: b331faa9d678
Create Date: 2026-09-02 19:14:40.996516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc589adf566c'
down_revision: Union[str, Sequence[str], None] = 'b331faa9d678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('type', mysql.ENUM('success_story', 'health_info', 'area_report'), nullable=False))
    # ### end Alembic commands ###
