"""add articles and director approval workflow

Revision ID: c497898a5337
Revises: de9b5df5d9c1
Create Date: 2026-08-02 08:05:58.408651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c497898a5337'
down_revision: Union[str, Sequence[str], None] = 'de9b5df5d9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('success_story', 'health_info', 'area_report', name='articletype'), nullable=False),
    sa.Column('patient_consent', sa.Boolean(), nullable=False),
    sa.Column('patient_name_hidden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='articlestatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_fulltext', 'articles', ['title', 'body'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tags')
    op.drop_index('ix_articles_fulltext', table_name='articles', mysql_prefix='FULLTEXT')
    op.drop_table('articles')
    # ### end Alembic commands ###
