"""upgrade article_media to full album model

Revision ID: cb958adc58be
Revises: 19026ce858ee
Create Date: 2026-08-28 20:07:19.410926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb958adc58be'
down_revision: Union[str, Sequence[str], None] = '19026ce858ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_media', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('article_media', sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('article_media', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('article_media', sa.Column('is_cover', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_media', 'is_cover')
    op.drop_column('article_media', 'caption')
    op.drop_column('article_media', 'order_index')
    op.drop_column('article_media', 'id')
    # ### end Alembic commands ###
