"""add ambulances and blood donors

Revision ID: de9b5df5d9c1
Revises: b63cf4a4597a
Create Date: 2026-08-02 07:41:23.707517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9b5df5d9c1'
down_revision: Union[str, Sequence[str], None] = 'b63cf4a4597a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('govt', 'private', 'ngo', name='vehicleownertype'), nullable=False),
    sa.Column('availability_status', sa.Boolean(), nullable=False),
    sa.Column('fare_per_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ac_available', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.Enum('a_pos', 'a_neg', 'b_pos', 'b_neg', 'ab_pos', 'ab_neg', 'o_pos', 'o_neg', name='bloodgroup'), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=False),
    sa.Column('last_donated_at', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('contact_visibility', sa.Enum('volunteers_only', 'public', name='contactvisibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_donors_blood_group'), 'blood_donors', ['blood_group'], unique=False)
    op.create_index(op.f('ix_blood_donors_is_available'), 'blood_donors', ['is_available'], unique=False)
    op.create_index(op.f('ix_blood_donors_upazila_id'), 'blood_donors', ['upazila_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_donors_upazila_id'), table_name='blood_donors')
    op.drop_index(op.f('ix_blood_donors_is_available'), table_name='blood_donors')
    op.drop_index(op.f('ix_blood_donors_blood_group'), table_name='blood_donors')
    op.drop_table('blood_donors')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
